# Run it using docker-compose -f mysql-dev-init-compose.yml up
version: '3.2'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 33060:3306
    container_name: uni-todo
    environment:
      MYSQL_ROOT_PASSWORD: UniTodo1234
      MYSQL_DATABASE: unitodo
      MYSQL_USER: unitodouser
      MYSQL_PASSWORD: UniTodo1234
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d