CREATE TABLE todoentity (
    Id int NOT NULL AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Done TINYINT(1) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DeletedAt DATETIME NULL,
    PRIMARY KEY (Id)
);