CREATE TABLE todoentity (
    id int NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    done TINYINT(1) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    PRIMARY KEY (Id)
);